service: aws-landaCrud-node

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-1:588738582603:table/BooksTable"
  

functions:
  createBook:
    handler: src/addBook.addBook
    events:
      - httpApi:
          path: /books
          method: post
  getBook:
    handler: src/getBooks.getBook
    events:
      - httpApi:
          path: /books/{BookID}
          method: get
  updateBook:
    handler: src/updateBook.updateBook
    events:
      - httpApi:
          path: /books/{BookID}
          method: put
  deleteBook:
    handler: src/deleteBook.deleteBook
    events:
      - httpApi:
          path: /books/{BookID}
          method: delete  
  listBooks:
    handler: src/listBooks.listBooks
    events:
      - httpApi:
          path: /books
          method: get

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BooksTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: BookID
            AttributeType: S
        KeySchema:
          - AttributeName: BookID
            KeyType: HASH